io:
  output_root: "../Results/CrossVal"
  run_name: "notmirrored_hthtl_htia_both"

data:
  traces_path: "/shares/locbp.chem.uzh/pabriv/AllRawMovies/GT/NewRepo/Grx1_HTHTL_HTIA_K20Ac_snap_optparam_001/ProteinTracesIN/Filtered"
  dataset:
    HTHTL:
      channels: ["minmax", "zscored"]
    HTIA:
      channels: ["minmax", "zscored"]


trim_end: 2000
max_traces_per_class: 10000
balance_train: true
balance_val: true
balance_test: true


compare:
  models: ["orig_conv_gru", "resnet1d", "tcn"]


cv:
  n_splits: 4
  shuffle: true
  seed: 840410


optimization:
  batch_size: 64
  lr: 0.0004
  weight_decay: 0.0004
  max_epochs: 500
  patience_limit: 10
  label_smoothing: 0.001

  early_stopping:
    auc_min_delta: 0.005
    loss_mode: "relative"
    loss_tolerance: 1.10
    auc_tolerance: 0.003
    loss_min_delta: 0.005

  threshold_metric: "argmax"





uncertainty:
  mc_dropout:
    enabled: true
    n_mc: 100
    wasserstein_threshold: 0.7


system:
  compile: false
  num_workers: 4
  seed: 840410
  n_gpus: 3


augmentation_sweep:
  enabled: true
  factors: [0, 3, 5]
  augmentation_params:
    time_warp_sigma: 0.05
    noise_sigma: 0.05
    magnitude_jitter: 0.05
    include_mirror: false
