traces_path: "/Volumes/MediumBerth/SalomePaperData/FinalDataset/FinalTraces/Grx1_HTHTL_HTIA_K20Ac_snap_optparam_001/ProteinTracesIN/Filtered"

proteins: ["HTHTL", "snap"]
channel: "minmax"

output_root: "../../Results/Controls/RandomForest"

gmm:
  proba: 0.9
  min_peak_width: 1
  frame_interval_ms: 30.0

random_forest:
  n_estimators: 500
  test_size: 0.20
  seed: 840410
  trace_loss: 50.0
